In [9]:
import numpy as np;

In [ ]:
l = np.array([[1, 2], [3, 4], [5, 6]])

# type(l)
# l.dtype
# l.shape
l.strides

(16, 8)

In [ ]:
l = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
l.shape
l.sum(axis=1) # sum rowwise

(3, 4)

In [ ]:
data = {
    "Maths": np.sum(l, axis = 1),
    "avg": np.average(l,axis = 1),
    "Max": np.max(l,axis = 1)
}
data

# axis = 1 will trigger rows
# axis = 0 will trigger columns

{'Maths': array([10, 26, 42]),
 'avg': array([ 2.5,  6.5, 10.5]),
 'Max': array([ 4,  8, 12])}

In [ ]:
# l.reshape(-1, 4) # -1 depicts that you dont know how many rows you want
# l.flatten()
# l.ravel()

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [ ]:
d = np.array([ # 3d array
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

d.shape # (depth, rows, columns)
        

(2, 2, 3)

In [29]:
# A1

td = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
td.shape

(1, 3, 3)

In [30]:
# A2

ttd = np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44],[55,66,77,88],[111,222,333,444],[555,666,777,888],[1111,2222,3333,44440],[5555,6666,7777,8888]])
ttd

array([[    1,     2,     3,     4],
       [    5,     6,     7,     8],
       [   11,    22,    33,    44],
       [   55,    66,    77,    88],
       [  111,   222,   333,   444],
       [  555,   666,   777,   888],
       [ 1111,  2222,  3333, 44440],
       [ 5555,  6666,  7777,  8888]])

In [36]:
ttd.reshape(-1,1)
ttd.reshape(1,32)

array([[    1,     2,     3,     4,     5,     6,     7,     8,    11,
           22,    33,    44,    55,    66,    77,    88,   111,   222,
          333,   444,   555,   666,   777,   888,  1111,  2222,  3333,
        44440,  5555,  6666,  7777,  8888]])

In [38]:
td.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [39]:
ttd.T

array([[    1,     5,    11,    55,   111,   555,  1111,  5555],
       [    2,     6,    22,    66,   222,   666,  2222,  6666],
       [    3,     7,    33,    77,   333,   777,  3333,  7777],
       [    4,     8,    44,    88,   444,   888, 44440,  8888]])