In [2]:
import numpy as np;

In [3]:
l = np.array([[1, 2], [3, 4], [5, 6]])

# type(l)
# l.dtype
# l.shape
l.strides

(16, 8)

In [4]:
l = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
l.shape
l.sum(axis=1) # sum rowwise

array([10, 26, 42, 58])

In [5]:
data = {
    "Maths": np.sum(l, axis = 1),
    "avg": np.average(l,axis = 1),
    "Max": np.max(l,axis = 1)
}
data

# axis = 1 will trigger rows
# axis = 0 will trigger columns

{'Maths': array([10, 26, 42, 58]),
 'avg': array([ 2.5,  6.5, 10.5, 14.5]),
 'Max': array([ 4,  8, 12, 16])}

In [6]:
# l.reshape(-1, 4) # -1 depicts that you dont know how many rows you want
# l.flatten()
# l.ravel()

In [7]:
d = np.array([ # 3d array
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

d.shape # (depth, rows, columns)
        

(2, 2, 3)

In [8]:
# A1

td = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
td.shape

(1, 3, 3)

In [9]:
# A2

ttd = np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44],[55,66,77,88],[111,222,333,444],[555,666,777,888],[1111,2222,3333,44440],[5555,6666,7777,8888]])
ttd

array([[    1,     2,     3,     4],
       [    5,     6,     7,     8],
       [   11,    22,    33,    44],
       [   55,    66,    77,    88],
       [  111,   222,   333,   444],
       [  555,   666,   777,   888],
       [ 1111,  2222,  3333, 44440],
       [ 5555,  6666,  7777,  8888]])

In [10]:
ttd.reshape(-1,1)
ttd.reshape(1,32)

array([[    1,     2,     3,     4,     5,     6,     7,     8,    11,
           22,    33,    44,    55,    66,    77,    88,   111,   222,
          333,   444,   555,   666,   777,   888,  1111,  2222,  3333,
        44440,  5555,  6666,  7777,  8888]])

In [11]:
td.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [12]:
ttd.T

array([[    1,     5,    11,    55,   111,   555,  1111,  5555],
       [    2,     6,    22,    66,   222,   666,  2222,  6666],
       [    3,     7,    33,    77,   333,   777,  3333,  7777],
       [    4,     8,    44,    88,   444,   888, 44440,  8888]])

In [16]:
mask = ttd>72
print(mask) # masking is a way to filter out data based on some condition. In this case, the mask will be a boolean array indicating which elements of td are greater than 72.
print(ttd[mask]) # this will print the elements of td that are greater than 72, which in this case will be an empty array since all elements of td are less than 72.
print(ttd[~mask]) # False Values

[[False False False False]
 [False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[   77    88   111   222   333   444   555   666   777   888  1111  2222
  3333 44440  5555  6666  7777  8888]
[ 1  2  3  4  5  6  7  8 11 22 33 44 55 66]


In [17]:
res = np.where(ttd > 100, "Big", "Small") 
res

array([['Small', 'Small', 'Small', 'Small'],
       ['Small', 'Small', 'Small', 'Small'],
       ['Small', 'Small', 'Small', 'Small'],
       ['Small', 'Small', 'Small', 'Small'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big']], dtype='<U5')

In [22]:
cond = [((ttd > 50) & (ttd < 70)), ((ttd >= 70) & (ttd <= 100))]
choice = ["S", "L"]
np.select(cond, choice, default = "Big")

array([['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big'],
       ['S', 'S', 'L', 'L'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big'],
       ['Big', 'Big', 'Big', 'Big']], dtype='<U3')